### ISSUE TITLE
Maximum Recursive Reached

### ISSUE THREAD

**Issue by Rlewisrlou666** [OpenPoGo/OpenPoGoBot#176]
### Expected Behavior

Running normally.
### Actual Behavior

After running for a little bit it throws up loads or walk/ step errors then crashes with maximum recursive reached.
### Steps to Reproduce

Run normally

**Comment by Saturate** [comment]
You should just update to the newest version, then this bug is fixed :)

**Comment by andythorne** [comment]
Saturate is right, update and try again. Reopen the issue if you still have the problem and post the error output.

**Comment by Rlewisrlou666** [comment]
Thanks for your help guys.

**Comment by Rlewisrlou666** [comment]
still getting same issue after update.

![snip20160802_1](https://cloud.githubusercontent.com/assets/20677921/17332998/a7b8ece0-58c8-11e6-9a49-a064bdf5ef6d.png)

**Comment by andythorne** [comment]
Thanks @Rlewisrlou666, I think we've found the issue and we'll get it fixed :)

**Comment by Rlewisrlou666** [comment]
I'm running again now and testing, it seems to be working now though.

another question have you fixed the ignore function I was getting concerned because it doesn't seem to be catching any pokemon.

Thanks again guys.

**Comment by Rlewisrlou666** [comment]
This is what it crashed on last time and threw up the recursive error.

![snip20160802_3](https://cloud.githubusercontent.com/assets/20677921/17334526/76c51464-58ce-11e6-83a9-46f8d3a09b48.png)

**Comment by andythorne** [comment]
Thanks, the error in that 2nd screenshot should definitely be fixed in the new version.

There could be a few reasons are aren't catching anything. If you can see it throwing balls but they keep running away, or you visit a pokestop and get no loot after spinning, you may be soft banned (you probably jumped location too far and they've caught you cheating).

If you copy a log here it may help identify the problem :)

**Comment by wchill** [comment]
@Rlewisrlou666 apparently Pokemon spawn timing has been significantly altered. It's unlikely that it's an issue on our side because after every testing session I seem to always transfer 30-40 Electabuzzes.

**Comment by Rlewisrlou666** [comment]
It seems to be fixed now I haven't had another issue that was the last time it crashed.
I think it was user error more than anything your end. lol

Aww I haven't caught a single Elecabuzz.
I'm forever transfering 30 odd Pidgey/Zubat/Drowzee.

I set up the catch-ignore.yml but its still catching unwanted Pokemon not a massive issue because I can just transfer or evolve them on my phone just wondering if you got it working.

You are doing amazing work guys and it makes it so much easier not having to walk around with the kids iPad.

**Comment by wchill** [comment]
`catch-ignore.yml` is not functional at the moment, so that's expected behavior.
